name: Manage Auto Merge

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  rename_pr_job:
    runs-on: ubuntu-latest
    name: Manage auto merge state
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Auto Merge
        uses: ./ # Uses an action in the root directory
        id: pr-auto-configuration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          activate-label: 'merge:auto'
          disabled-label: 'merge:manual'
          strategy: 'SQUASH'