name: Manage Auto Merge

on:
  pull_request:
    types: [labeled, unlabeled, auto_merge_enabled]

jobs:
  manage_automerge_state:
    runs-on: [self-hosted, cybergrx-runner]
    name: Manage auto merge state
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.3
        with:
          app_id: ${{ secrets.EKS_ACTION_WORKER_APP_ID }}
          private_key: ${{ secrets.EKS_ACTION_WORKER_PRIVATE_KEY }}
      - name: Configure Auto Merge
        uses: ./ # Uses an action in the root directory
        id: pr-auto-configuration
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          activate-label: 'merge:auto'
          disabled-label: 'merge:manual'
          strategy: 'SQUASH'